language: c++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

osx_image: xcode7.3

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install freeglut3-dev libsndfile1-dev libopenal-dev libxrandr-dev
    fi

install: ./setup.sh

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cd code/build/mac/gmake
    else
      cd code/build/linux/gmake
    fi
  - make --config=debug64
  - make --config=profile64
  - make --config=release64
